version: "3"
services:
  cadastro_backend:
    build:
      dockerfile: Dockerfile
      context: .
    image: cadastro-backend
    container_name: cadastro-backend
    depends_on: [postgres]
    ports:
      - "8080:8080"
    networks:
      - cadastro_network
  postgres:
    image: postgres
    restart: always
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=cadastro"
    container_name: postgres
    networks:
      - cadastro_network
    ports:
      - "5432:5432"
networks:
  cadastro_network:
    driver: bridge